DROP TABLE IF EXISTS "products";

CREATE TABLE "products" (
  "ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
  "NAME" VARCHAR(100) NOT NULL,
  "DESCRIPTION" VARCHAR(255),
  "PRICE" DECIMAL(10,2) NOT NULL DEFAULT 0,
  "QUANTITY" INT NOT NULL DEFAULT 0,
  "CREATED_AT" TIMESTAMP NULL
);